auto-update: true
server-name: A Minecraft Server
website:
  url: http://minecraft.net
  enable-broadcast: true
vote:
  url: http://minecraft-server-list.com
  enable-broadcast: true
shop:
  url: http://buycraft.net
  enable-broadcast: true
facebook:
  url: http://facebook.com
  enable-broadcast: true
twitter:
  url: http://twitter.com
  enable-broadcast: true
youtube:
  url: http://youtube.com
  enable-broadcast: true
instagram:
  url: http://instagram.com
  enable-broadcast: true
link:
  name: Encyclopedia
  url: http://google.com
  enable-broadcast: true