name: PlayerLink
description: PlayerLink is a Bukkit plugin designed to keep your players informed about your server.
author: jflory7
website: http://dev.bukkit.org/bukkit-plugins/playerlink/
main: com.crystalcraftmc.playerlink.Main
version: 1.3

commands:
   playerlink:
      description: Includes info and reloads.
      usage: /playerlink <help, reload>
   website:
      description: Shows the link to a website you set.
      usage: /website
      permission: playerlink.website
      permission-message: You don't have <permission>
   vote:
      description: Shows the link to a voting website you set.
      usage: /vote
      permission: playerlink.vote
      permission-message: You don't have <permission>
   shop:
      description: Shows the link to a server shop you set.
      usage: /shop
      permission: playerlink.shop
      permission-message: You don't have <permission>
   facebook:
      description: Shows the link to a Facebook page.
      usage: /facebook
      permission: playerlink.facebook
      permission-message: You don't have <permission>
   twitter:
      description: Shows the link to a Twitter page.
      usage: /twitter
      permission: playerlink.twitter
      permission-message: You don't have <permission>
   youtube:
      description: Shows the link to a YouTube page.
      usage: /youtube
      permission: playerlink.youtube
      permission-message: You don't have <permission>
   instagram:
      description: Shows the link to an Instagram page you set.
      usage: /instagram
      permission: playerlink.instagram
      permission-message: You don't have <permission>
   link:
      description: Shows the link to any URL you set.
      usage: /link
      permission: playerlink.link
      permission-message: You don't have <permission>

permissions:
    playerlink.*:
        description: Gives access to all PlayerLink commands.
        children:
            playerlink.player.*: true
            playerlink.reload: true
    playerlink.player.*:
        description: Gives access to all commands for players.
        children:
            playerlink.help: true
            playerlink.website: true
            playerlink.vote: true
            playerlink.shop: true
            playerlink.facebook: true
            playerlink.twitter: true
            playerlink.youtube: true
            playerlink.instagram: true
            playerlink.link: true
            playerlink.reload: false
    playerlink.help:
        description: Show a list of commands for PlayerLink.
        default: op
    playerlink.website:
        description: Shows the link to a website you set.
        default: op
    playerlink.vote:
        description: Shows the link to a voting website you set.
        default: op
    playerlink.shop:
        description: Shows the link to a server shop you set.
        default: op
    playerlink.facebook:
        description: Shows the link to a Facebook page you set.
        default: op
    playerlink.twitter:
        description: Shows the link to a Twitter page you set.
        default: op
    playerlink.youtube:
        description: Shows the link to a YouTube page you set.
        default: op
    playerlink.instagram:
        description: Shows the link to an Instagram page you set.
        default: op
    playerlink.link:
        description: Shows the link to any URL you set.
        default: op
    playerlink.reload:
        description: Reload the configuration.
        default: op